export const browserCoreExamples = [
  "maumau browser status",
  "maumau browser start",
  "maumau browser stop",
  "maumau browser tabs",
  "maumau browser open https://example.com",
  "maumau browser focus abcd1234",
  "maumau browser close abcd1234",
  "maumau browser screenshot",
  "maumau browser screenshot --full-page",
  "maumau browser screenshot --ref 12",
  "maumau browser snapshot",
  "maumau browser snapshot --format aria --limit 200",
  "maumau browser snapshot --efficient",
  "maumau browser snapshot --labels",
];

export const browserActionExamples = [
  "maumau browser navigate https://example.com",
  "maumau browser resize 1280 720",
  "maumau browser click 12 --double",
  'maumau browser type 23 "hello" --submit',
  "maumau browser press Enter",
  "maumau browser hover 44",
  "maumau browser drag 10 11",
  "maumau browser select 9 OptionA OptionB",
  "maumau browser upload /tmp/maumau/uploads/file.pdf",
  'maumau browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "maumau browser dialog --accept",
  'maumau browser wait --text "Done"',
  "maumau browser evaluate --fn '(el) => el.textContent' --ref 7",
  "maumau browser console --level error",
  "maumau browser pdf",
];
