import { createHash } from "node:crypto";

// Curated word lists for deterministic, friendly Mauworld handles.
// Each install gets a stable adjective-creature-place handle derived from its
// device id. No numbers, no punctuation other than hyphens, lowercase only.

const ADJECTIVES = [
  "amber",
  "ancient",
  "balmy",
  "bashful",
  "bouncy",
  "breezy",
  "bright",
  "brisk",
  "bubbly",
  "calm",
  "candid",
  "cheery",
  "chilly",
  "clever",
  "cozy",
  "crisp",
  "dapper",
  "dawning",
  "dewy",
  "dreamy",
  "drifting",
  "dusky",
  "earnest",
  "easy",
  "feisty",
  "fern",
  "festive",
  "fluffy",
  "foggy",
  "frosty",
  "gentle",
  "glowing",
  "golden",
  "grassy",
  "happy",
  "hardy",
  "hazel",
  "hearty",
  "hidden",
  "honest",
  "humble",
  "jaunty",
  "jolly",
  "kindly",
  "lively",
  "loamy",
  "lofty",
  "lucky",
  "merry",
  "minty",
  "misty",
  "moonlit",
  "mossy",
  "nimble",
  "nutty",
  "olive",
  "peachy",
  "pearly",
  "perky",
  "plucky",
  "polite",
  "quiet",
  "rainy",
  "rosy",
  "rugged",
  "rustic",
  "salty",
  "sandy",
  "sleepy",
  "snowy",
  "snug",
  "soft",
  "spry",
  "starlit",
  "steady",
  "stormy",
  "sturdy",
  "sunny",
  "sweet",
  "swift",
  "tangy",
  "tender",
  "tidy",
  "tipsy",
  "twilit",
  "velvet",
  "verdant",
  "warm",
  "whimsy",
  "wild",
  "windy",
  "wise",
  "woolly",
  "zealous",
  "zesty",
] as const;

const CREATURES = [
  "badger",
  "beaver",
  "bison",
  "bluejay",
  "bobcat",
  "buffalo",
  "bumblebee",
  "butterfly",
  "capybara",
  "caribou",
  "chipmunk",
  "cormorant",
  "coyote",
  "crane",
  "crow",
  "deer",
  "dingo",
  "dolphin",
  "dormouse",
  "duck",
  "eagle",
  "ferret",
  "finch",
  "firefly",
  "flamingo",
  "fox",
  "frog",
  "gecko",
  "giraffe",
  "goose",
  "gosling",
  "grouse",
  "hare",
  "hawk",
  "hedgehog",
  "heron",
  "hummingbird",
  "ibex",
  "jackrabbit",
  "jay",
  "kingfisher",
  "kiwi",
  "koala",
  "lemur",
  "lynx",
  "macaw",
  "magpie",
  "mallard",
  "manatee",
  "marmot",
  "marten",
  "meerkat",
  "mockingbird",
  "moose",
  "newt",
  "nightingale",
  "ocelot",
  "octopus",
  "opossum",
  "orca",
  "otter",
  "owl",
  "panda",
  "pangolin",
  "parakeet",
  "partridge",
  "penguin",
  "platypus",
  "porcupine",
  "puffin",
  "quokka",
  "rabbit",
  "raccoon",
  "raven",
  "redstart",
  "robin",
  "salamander",
  "salmon",
  "sandpiper",
  "seal",
  "shrew",
  "skunk",
  "sparrow",
  "squirrel",
  "starling",
  "stoat",
  "stork",
  "swallow",
  "swan",
  "tanager",
  "tapir",
  "thrush",
  "tortoise",
  "toucan",
  "turtle",
  "walrus",
  "warbler",
  "weasel",
  "whale",
  "wolf",
  "wombat",
  "wren",
] as const;

const PLACES = [
  "alcove",
  "atoll",
  "bayou",
  "beach",
  "bluff",
  "bog",
  "boulder",
  "branch",
  "brook",
  "burrow",
  "canopy",
  "canyon",
  "cliff",
  "cloud",
  "clover",
  "coast",
  "comet",
  "cove",
  "creek",
  "crest",
  "delta",
  "dell",
  "den",
  "desert",
  "dewdrop",
  "dune",
  "dusk",
  "ember",
  "estuary",
  "fawn",
  "fern",
  "field",
  "fjord",
  "flame",
  "forest",
  "fountain",
  "garden",
  "geyser",
  "glade",
  "glen",
  "grove",
  "harbor",
  "haven",
  "headland",
  "hearth",
  "hedge",
  "hill",
  "hollow",
  "horizon",
  "inlet",
  "island",
  "lagoon",
  "lake",
  "lantern",
  "ledge",
  "marsh",
  "meadow",
  "meridian",
  "mesa",
  "mire",
  "moor",
  "mountain",
  "nebula",
  "oasis",
  "orchard",
  "outcrop",
  "pasture",
  "path",
  "pebble",
  "pier",
  "pinegrove",
  "plateau",
  "plume",
  "pond",
  "prairie",
  "quarry",
  "ravine",
  "reef",
  "ridge",
  "river",
  "saltflat",
  "sanctuary",
  "savanna",
  "shore",
  "skyline",
  "spring",
  "starfield",
  "steppe",
  "summit",
  "swamp",
  "thicket",
  "tidepool",
  "trail",
  "tundra",
  "vale",
  "valley",
  "wetland",
  "willow",
  "windbreak",
] as const;

function pickFromList<T extends readonly string[]>(list: T, hashSlice: string): T[number] {
  // Convert hex slice into a non-negative integer. We mod by list length to
  // pick a stable index.
  const numeric = Number.parseInt(hashSlice, 16);
  const safe = Number.isFinite(numeric) ? numeric : 0;
  return list[safe % list.length] as T[number];
}

/**
 * Generate a deterministic, human-friendly Mauworld handle for an install.
 *
 * Same `deviceId` always produces the same handle. Format is
 * `<adjective>-<creature>-<place>`, lowercase, hyphenated, no digits.
 */
export function generateInstallUsername(deviceId: string): string {
  const trimmed = (deviceId ?? "").trim();
  if (!trimmed) {
    throw new Error("generateInstallUsername: deviceId is required");
  }
  const digest = createHash("sha256").update(trimmed).digest("hex");
  const adj = pickFromList(ADJECTIVES, digest.slice(0, 8));
  const creature = pickFromList(CREATURES, digest.slice(8, 16));
  const place = pickFromList(PLACES, digest.slice(16, 24));
  return `${adj}-${creature}-${place}`;
}
